version: "3.9"

services:
  backend:
    build:
      context: ./backend   # path to backend folder
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  # path to frontend folder
      dockerfile: Dockerfile
    ports:
      - "5173:80"   # maps localhost:5173 → container:80 (nginx)
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
